name: Publish to ComfyUI Registry

on:
  push:
    branches: [main]
    paths:
      - "pyproject.toml"
  workflow_dispatch:

permissions:
  issues: write

jobs:
  publish:
    name: Publish Custom Node
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'laboratoiresonore' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Publish to Comfy Registry
        uses: Comfy-Org/publish-node-action@v1
        with:
          personal_access_token: ${{ secrets.REGISTRY_ACCESS_TOKEN }}
